project:
  type: website
  output-dir: docs

website:
  title: "Eugen Pissarskoi"
  description: Ethik Nachhaltiger Entwicklung -- Argumentatanalyse
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Startseite
      - href: forschung.qmd
        text: Inhalte
      - href: wiss-aktivit.qmd
        text: Gesch√§ftigkeit
      - href: lebenslauf.qmd
        text: Lebenslauf
  page-footer:
    left: "Eugen Pissarskoi, 2024"
    center: 
      - text: "Impressum"
        href: about.qmd
      - text: "Datenschutz"
        href: datenschutz.qmd

format:
  html:
    theme: 
      light: sandstone
      dark: solar
    css: styles.css
    toc: true
    hyphenate: true

execute:
  freeze: auto



